---

user: ubuntu

allow_blockscout_ssh: true
allow_blockscout_p2p: true
allow_blockscout_http: true

username: "netagent"
users:
- name: "{{ username }}"
home: "/home/{{ username }}"

MAIN_REPO_FETCH: "poanetwork"

reboot_after_completion: false
install_debug_tools: "no"
install_firewall: false

netstats_agent_version: "master"
agent_executable_url: "https://4r45ow.dm.files.1drv.com/y4mLS_qgxty6U8OSRgo2TiY_ctA_ulKE_h7q6YB5O2RVutBy1YuycZpnUJFTff1qYuOLL7vCQcZfOuxZ66Dr9SFayRC-FWjZFf9dMSycKEB1qkDX-xd8pkp09ujme5FLfDOc353FP1fu699YsTf9EYf9Lh_TocXfVXqT0cmOwtz5qmoadigTIfSW1TF8kxqGON7/poa_agent.tar.gz?download&psid=1"

create_user: false
agent_user: "FKtzHQt4"
agent_password: "Xd7qR9gAtV5T5bK"
